/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccettaInvitoRouteImport } from './routes/accetta-invito'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSubappaltatoriRouteImport } from './routes/_authenticated/subappaltatori'
import { Route as AuthenticatedScadenziarioRouteImport } from './routes/_authenticated/scadenziario'
import { Route as AuthenticatedRapportiniRouteImport } from './routes/_authenticated/rapportini'
import { Route as AuthenticatedProfiloRouteImport } from './routes/_authenticated/profilo'
import { Route as AuthenticatedOrganizzazioneRouteImport } from './routes/_authenticated/organizzazione'
import { Route as AuthenticatedNotificheRouteImport } from './routes/_authenticated/notifiche'
import { Route as AuthenticatedMaterialiRouteImport } from './routes/_authenticated/materiali'
import { Route as AuthenticatedFornitoriRouteImport } from './routes/_authenticated/fornitori'
import { Route as AuthenticatedDocumentiRouteImport } from './routes/_authenticated/documenti'
import { Route as AuthenticatedCostiStrutturaRouteImport } from './routes/_authenticated/costi-struttura'
import { Route as AuthenticatedCostiPersonaleRouteImport } from './routes/_authenticated/costi-personale'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedRapportiniIndexRouteImport } from './routes/_authenticated/rapportini.index'
import { Route as AuthenticatedPreventiviIndexRouteImport } from './routes/_authenticated/preventivi.index'
import { Route as AuthenticatedDocumentiIndexRouteImport } from './routes/_authenticated/documenti.index'
import { Route as AuthenticatedCommesseIndexRouteImport } from './routes/_authenticated/commesse.index'
import { Route as AuthenticatedClientiIndexRouteImport } from './routes/_authenticated/clienti.index'
import { Route as AuthenticatedRapportiniRapportinoIdRouteImport } from './routes/_authenticated/rapportini.$rapportinoId'
import { Route as AuthenticatedPreventiviIdRouteImport } from './routes/_authenticated/preventivi.$id'
import { Route as AuthenticatedDocumentiDocumentoIdRouteImport } from './routes/_authenticated/documenti.$documentoId'
import { Route as AuthenticatedCommesseCommessaIdRouteImport } from './routes/_authenticated/commesse.$commessaId'
import { Route as AuthenticatedClientiClienteIdRouteImport } from './routes/_authenticated/clienti.$clienteId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccettaInvitoRoute = AccettaInvitoRouteImport.update({
  id: '/accetta-invito',
  path: '/accetta-invito',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubappaltatoriRoute =
  AuthenticatedSubappaltatoriRouteImport.update({
    id: '/subappaltatori',
    path: '/subappaltatori',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScadenziarioRoute =
  AuthenticatedScadenziarioRouteImport.update({
    id: '/scadenziario',
    path: '/scadenziario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRapportiniRoute = AuthenticatedRapportiniRouteImport.update({
  id: '/rapportini',
  path: '/rapportini',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfiloRoute = AuthenticatedProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizzazioneRoute =
  AuthenticatedOrganizzazioneRouteImport.update({
    id: '/organizzazione',
    path: '/organizzazione',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificheRoute = AuthenticatedNotificheRouteImport.update({
  id: '/notifiche',
  path: '/notifiche',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialiRoute = AuthenticatedMaterialiRouteImport.update({
  id: '/materiali',
  path: '/materiali',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornitoriRoute = AuthenticatedFornitoriRouteImport.update({
  id: '/fornitori',
  path: '/fornitori',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentiRoute = AuthenticatedDocumentiRouteImport.update({
  id: '/documenti',
  path: '/documenti',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCostiStrutturaRoute =
  AuthenticatedCostiStrutturaRouteImport.update({
    id: '/costi-struttura',
    path: '/costi-struttura',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCostiPersonaleRoute =
  AuthenticatedCostiPersonaleRouteImport.update({
    id: '/costi-personale',
    path: '/costi-personale',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRapportiniIndexRoute =
  AuthenticatedRapportiniIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRapportiniRoute,
  } as any)
const AuthenticatedPreventiviIndexRoute =
  AuthenticatedPreventiviIndexRouteImport.update({
    id: '/preventivi/',
    path: '/preventivi/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentiIndexRoute =
  AuthenticatedDocumentiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDocumentiRoute,
  } as any)
const AuthenticatedCommesseIndexRoute =
  AuthenticatedCommesseIndexRouteImport.update({
    id: '/commesse/',
    path: '/commesse/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientiIndexRoute =
  AuthenticatedClientiIndexRouteImport.update({
    id: '/clienti/',
    path: '/clienti/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRapportiniRapportinoIdRoute =
  AuthenticatedRapportiniRapportinoIdRouteImport.update({
    id: '/$rapportinoId',
    path: '/$rapportinoId',
    getParentRoute: () => AuthenticatedRapportiniRoute,
  } as any)
const AuthenticatedPreventiviIdRoute =
  AuthenticatedPreventiviIdRouteImport.update({
    id: '/preventivi/$id',
    path: '/preventivi/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentiDocumentoIdRoute =
  AuthenticatedDocumentiDocumentoIdRouteImport.update({
    id: '/$documentoId',
    path: '/$documentoId',
    getParentRoute: () => AuthenticatedDocumentiRoute,
  } as any)
const AuthenticatedCommesseCommessaIdRoute =
  AuthenticatedCommesseCommessaIdRouteImport.update({
    id: '/commesse/$commessaId',
    path: '/commesse/$commessaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientiClienteIdRoute =
  AuthenticatedClientiClienteIdRouteImport.update({
    id: '/clienti/$clienteId',
    path: '/clienti/$clienteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/accetta-invito': typeof AccettaInvitoRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/costi-personale': typeof AuthenticatedCostiPersonaleRoute
  '/costi-struttura': typeof AuthenticatedCostiStrutturaRoute
  '/documenti': typeof AuthenticatedDocumentiRouteWithChildren
  '/fornitori': typeof AuthenticatedFornitoriRoute
  '/materiali': typeof AuthenticatedMaterialiRoute
  '/notifiche': typeof AuthenticatedNotificheRoute
  '/organizzazione': typeof AuthenticatedOrganizzazioneRoute
  '/profilo': typeof AuthenticatedProfiloRoute
  '/rapportini': typeof AuthenticatedRapportiniRouteWithChildren
  '/scadenziario': typeof AuthenticatedScadenziarioRoute
  '/subappaltatori': typeof AuthenticatedSubappaltatoriRoute
  '/clienti/$clienteId': typeof AuthenticatedClientiClienteIdRoute
  '/commesse/$commessaId': typeof AuthenticatedCommesseCommessaIdRoute
  '/documenti/$documentoId': typeof AuthenticatedDocumentiDocumentoIdRoute
  '/preventivi/$id': typeof AuthenticatedPreventiviIdRoute
  '/rapportini/$rapportinoId': typeof AuthenticatedRapportiniRapportinoIdRoute
  '/clienti/': typeof AuthenticatedClientiIndexRoute
  '/commesse/': typeof AuthenticatedCommesseIndexRoute
  '/documenti/': typeof AuthenticatedDocumentiIndexRoute
  '/preventivi/': typeof AuthenticatedPreventiviIndexRoute
  '/rapportini/': typeof AuthenticatedRapportiniIndexRoute
}
export interface FileRoutesByTo {
  '/accetta-invito': typeof AccettaInvitoRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/costi-personale': typeof AuthenticatedCostiPersonaleRoute
  '/costi-struttura': typeof AuthenticatedCostiStrutturaRoute
  '/fornitori': typeof AuthenticatedFornitoriRoute
  '/materiali': typeof AuthenticatedMaterialiRoute
  '/notifiche': typeof AuthenticatedNotificheRoute
  '/organizzazione': typeof AuthenticatedOrganizzazioneRoute
  '/profilo': typeof AuthenticatedProfiloRoute
  '/scadenziario': typeof AuthenticatedScadenziarioRoute
  '/subappaltatori': typeof AuthenticatedSubappaltatoriRoute
  '/': typeof AuthenticatedIndexRoute
  '/clienti/$clienteId': typeof AuthenticatedClientiClienteIdRoute
  '/commesse/$commessaId': typeof AuthenticatedCommesseCommessaIdRoute
  '/documenti/$documentoId': typeof AuthenticatedDocumentiDocumentoIdRoute
  '/preventivi/$id': typeof AuthenticatedPreventiviIdRoute
  '/rapportini/$rapportinoId': typeof AuthenticatedRapportiniRapportinoIdRoute
  '/clienti': typeof AuthenticatedClientiIndexRoute
  '/commesse': typeof AuthenticatedCommesseIndexRoute
  '/documenti': typeof AuthenticatedDocumentiIndexRoute
  '/preventivi': typeof AuthenticatedPreventiviIndexRoute
  '/rapportini': typeof AuthenticatedRapportiniIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accetta-invito': typeof AccettaInvitoRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/costi-personale': typeof AuthenticatedCostiPersonaleRoute
  '/_authenticated/costi-struttura': typeof AuthenticatedCostiStrutturaRoute
  '/_authenticated/documenti': typeof AuthenticatedDocumentiRouteWithChildren
  '/_authenticated/fornitori': typeof AuthenticatedFornitoriRoute
  '/_authenticated/materiali': typeof AuthenticatedMaterialiRoute
  '/_authenticated/notifiche': typeof AuthenticatedNotificheRoute
  '/_authenticated/organizzazione': typeof AuthenticatedOrganizzazioneRoute
  '/_authenticated/profilo': typeof AuthenticatedProfiloRoute
  '/_authenticated/rapportini': typeof AuthenticatedRapportiniRouteWithChildren
  '/_authenticated/scadenziario': typeof AuthenticatedScadenziarioRoute
  '/_authenticated/subappaltatori': typeof AuthenticatedSubappaltatoriRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clienti/$clienteId': typeof AuthenticatedClientiClienteIdRoute
  '/_authenticated/commesse/$commessaId': typeof AuthenticatedCommesseCommessaIdRoute
  '/_authenticated/documenti/$documentoId': typeof AuthenticatedDocumentiDocumentoIdRoute
  '/_authenticated/preventivi/$id': typeof AuthenticatedPreventiviIdRoute
  '/_authenticated/rapportini/$rapportinoId': typeof AuthenticatedRapportiniRapportinoIdRoute
  '/_authenticated/clienti/': typeof AuthenticatedClientiIndexRoute
  '/_authenticated/commesse/': typeof AuthenticatedCommesseIndexRoute
  '/_authenticated/documenti/': typeof AuthenticatedDocumentiIndexRoute
  '/_authenticated/preventivi/': typeof AuthenticatedPreventiviIndexRoute
  '/_authenticated/rapportini/': typeof AuthenticatedRapportiniIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accetta-invito'
    | '/auth'
    | '/reset-password'
    | '/audit'
    | '/costi-personale'
    | '/costi-struttura'
    | '/documenti'
    | '/fornitori'
    | '/materiali'
    | '/notifiche'
    | '/organizzazione'
    | '/profilo'
    | '/rapportini'
    | '/scadenziario'
    | '/subappaltatori'
    | '/clienti/$clienteId'
    | '/commesse/$commessaId'
    | '/documenti/$documentoId'
    | '/preventivi/$id'
    | '/rapportini/$rapportinoId'
    | '/clienti/'
    | '/commesse/'
    | '/documenti/'
    | '/preventivi/'
    | '/rapportini/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accetta-invito'
    | '/auth'
    | '/reset-password'
    | '/audit'
    | '/costi-personale'
    | '/costi-struttura'
    | '/fornitori'
    | '/materiali'
    | '/notifiche'
    | '/organizzazione'
    | '/profilo'
    | '/scadenziario'
    | '/subappaltatori'
    | '/'
    | '/clienti/$clienteId'
    | '/commesse/$commessaId'
    | '/documenti/$documentoId'
    | '/preventivi/$id'
    | '/rapportini/$rapportinoId'
    | '/clienti'
    | '/commesse'
    | '/documenti'
    | '/preventivi'
    | '/rapportini'
  id:
    | '__root__'
    | '/_authenticated'
    | '/accetta-invito'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/audit'
    | '/_authenticated/costi-personale'
    | '/_authenticated/costi-struttura'
    | '/_authenticated/documenti'
    | '/_authenticated/fornitori'
    | '/_authenticated/materiali'
    | '/_authenticated/notifiche'
    | '/_authenticated/organizzazione'
    | '/_authenticated/profilo'
    | '/_authenticated/rapportini'
    | '/_authenticated/scadenziario'
    | '/_authenticated/subappaltatori'
    | '/_authenticated/'
    | '/_authenticated/clienti/$clienteId'
    | '/_authenticated/commesse/$commessaId'
    | '/_authenticated/documenti/$documentoId'
    | '/_authenticated/preventivi/$id'
    | '/_authenticated/rapportini/$rapportinoId'
    | '/_authenticated/clienti/'
    | '/_authenticated/commesse/'
    | '/_authenticated/documenti/'
    | '/_authenticated/preventivi/'
    | '/_authenticated/rapportini/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccettaInvitoRoute: typeof AccettaInvitoRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accetta-invito': {
      id: '/accetta-invito'
      path: '/accetta-invito'
      fullPath: '/accetta-invito'
      preLoaderRoute: typeof AccettaInvitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subappaltatori': {
      id: '/_authenticated/subappaltatori'
      path: '/subappaltatori'
      fullPath: '/subappaltatori'
      preLoaderRoute: typeof AuthenticatedSubappaltatoriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scadenziario': {
      id: '/_authenticated/scadenziario'
      path: '/scadenziario'
      fullPath: '/scadenziario'
      preLoaderRoute: typeof AuthenticatedScadenziarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapportini': {
      id: '/_authenticated/rapportini'
      path: '/rapportini'
      fullPath: '/rapportini'
      preLoaderRoute: typeof AuthenticatedRapportiniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profilo': {
      id: '/_authenticated/profilo'
      path: '/profilo'
      fullPath: '/profilo'
      preLoaderRoute: typeof AuthenticatedProfiloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizzazione': {
      id: '/_authenticated/organizzazione'
      path: '/organizzazione'
      fullPath: '/organizzazione'
      preLoaderRoute: typeof AuthenticatedOrganizzazioneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifiche': {
      id: '/_authenticated/notifiche'
      path: '/notifiche'
      fullPath: '/notifiche'
      preLoaderRoute: typeof AuthenticatedNotificheRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiali': {
      id: '/_authenticated/materiali'
      path: '/materiali'
      fullPath: '/materiali'
      preLoaderRoute: typeof AuthenticatedMaterialiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornitori': {
      id: '/_authenticated/fornitori'
      path: '/fornitori'
      fullPath: '/fornitori'
      preLoaderRoute: typeof AuthenticatedFornitoriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documenti': {
      id: '/_authenticated/documenti'
      path: '/documenti'
      fullPath: '/documenti'
      preLoaderRoute: typeof AuthenticatedDocumentiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/costi-struttura': {
      id: '/_authenticated/costi-struttura'
      path: '/costi-struttura'
      fullPath: '/costi-struttura'
      preLoaderRoute: typeof AuthenticatedCostiStrutturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/costi-personale': {
      id: '/_authenticated/costi-personale'
      path: '/costi-personale'
      fullPath: '/costi-personale'
      preLoaderRoute: typeof AuthenticatedCostiPersonaleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapportini/': {
      id: '/_authenticated/rapportini/'
      path: '/'
      fullPath: '/rapportini/'
      preLoaderRoute: typeof AuthenticatedRapportiniIndexRouteImport
      parentRoute: typeof AuthenticatedRapportiniRoute
    }
    '/_authenticated/preventivi/': {
      id: '/_authenticated/preventivi/'
      path: '/preventivi'
      fullPath: '/preventivi/'
      preLoaderRoute: typeof AuthenticatedPreventiviIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documenti/': {
      id: '/_authenticated/documenti/'
      path: '/'
      fullPath: '/documenti/'
      preLoaderRoute: typeof AuthenticatedDocumentiIndexRouteImport
      parentRoute: typeof AuthenticatedDocumentiRoute
    }
    '/_authenticated/commesse/': {
      id: '/_authenticated/commesse/'
      path: '/commesse'
      fullPath: '/commesse/'
      preLoaderRoute: typeof AuthenticatedCommesseIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clienti/': {
      id: '/_authenticated/clienti/'
      path: '/clienti'
      fullPath: '/clienti/'
      preLoaderRoute: typeof AuthenticatedClientiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapportini/$rapportinoId': {
      id: '/_authenticated/rapportini/$rapportinoId'
      path: '/$rapportinoId'
      fullPath: '/rapportini/$rapportinoId'
      preLoaderRoute: typeof AuthenticatedRapportiniRapportinoIdRouteImport
      parentRoute: typeof AuthenticatedRapportiniRoute
    }
    '/_authenticated/preventivi/$id': {
      id: '/_authenticated/preventivi/$id'
      path: '/preventivi/$id'
      fullPath: '/preventivi/$id'
      preLoaderRoute: typeof AuthenticatedPreventiviIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documenti/$documentoId': {
      id: '/_authenticated/documenti/$documentoId'
      path: '/$documentoId'
      fullPath: '/documenti/$documentoId'
      preLoaderRoute: typeof AuthenticatedDocumentiDocumentoIdRouteImport
      parentRoute: typeof AuthenticatedDocumentiRoute
    }
    '/_authenticated/commesse/$commessaId': {
      id: '/_authenticated/commesse/$commessaId'
      path: '/commesse/$commessaId'
      fullPath: '/commesse/$commessaId'
      preLoaderRoute: typeof AuthenticatedCommesseCommessaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clienti/$clienteId': {
      id: '/_authenticated/clienti/$clienteId'
      path: '/clienti/$clienteId'
      fullPath: '/clienti/$clienteId'
      preLoaderRoute: typeof AuthenticatedClientiClienteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedDocumentiRouteChildren {
  AuthenticatedDocumentiDocumentoIdRoute: typeof AuthenticatedDocumentiDocumentoIdRoute
  AuthenticatedDocumentiIndexRoute: typeof AuthenticatedDocumentiIndexRoute
}

const AuthenticatedDocumentiRouteChildren: AuthenticatedDocumentiRouteChildren =
  {
    AuthenticatedDocumentiDocumentoIdRoute:
      AuthenticatedDocumentiDocumentoIdRoute,
    AuthenticatedDocumentiIndexRoute: AuthenticatedDocumentiIndexRoute,
  }

const AuthenticatedDocumentiRouteWithChildren =
  AuthenticatedDocumentiRoute._addFileChildren(
    AuthenticatedDocumentiRouteChildren,
  )

interface AuthenticatedRapportiniRouteChildren {
  AuthenticatedRapportiniRapportinoIdRoute: typeof AuthenticatedRapportiniRapportinoIdRoute
  AuthenticatedRapportiniIndexRoute: typeof AuthenticatedRapportiniIndexRoute
}

const AuthenticatedRapportiniRouteChildren: AuthenticatedRapportiniRouteChildren =
  {
    AuthenticatedRapportiniRapportinoIdRoute:
      AuthenticatedRapportiniRapportinoIdRoute,
    AuthenticatedRapportiniIndexRoute: AuthenticatedRapportiniIndexRoute,
  }

const AuthenticatedRapportiniRouteWithChildren =
  AuthenticatedRapportiniRoute._addFileChildren(
    AuthenticatedRapportiniRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCostiPersonaleRoute: typeof AuthenticatedCostiPersonaleRoute
  AuthenticatedCostiStrutturaRoute: typeof AuthenticatedCostiStrutturaRoute
  AuthenticatedDocumentiRoute: typeof AuthenticatedDocumentiRouteWithChildren
  AuthenticatedFornitoriRoute: typeof AuthenticatedFornitoriRoute
  AuthenticatedMaterialiRoute: typeof AuthenticatedMaterialiRoute
  AuthenticatedNotificheRoute: typeof AuthenticatedNotificheRoute
  AuthenticatedOrganizzazioneRoute: typeof AuthenticatedOrganizzazioneRoute
  AuthenticatedProfiloRoute: typeof AuthenticatedProfiloRoute
  AuthenticatedRapportiniRoute: typeof AuthenticatedRapportiniRouteWithChildren
  AuthenticatedScadenziarioRoute: typeof AuthenticatedScadenziarioRoute
  AuthenticatedSubappaltatoriRoute: typeof AuthenticatedSubappaltatoriRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientiClienteIdRoute: typeof AuthenticatedClientiClienteIdRoute
  AuthenticatedCommesseCommessaIdRoute: typeof AuthenticatedCommesseCommessaIdRoute
  AuthenticatedPreventiviIdRoute: typeof AuthenticatedPreventiviIdRoute
  AuthenticatedClientiIndexRoute: typeof AuthenticatedClientiIndexRoute
  AuthenticatedCommesseIndexRoute: typeof AuthenticatedCommesseIndexRoute
  AuthenticatedPreventiviIndexRoute: typeof AuthenticatedPreventiviIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCostiPersonaleRoute: AuthenticatedCostiPersonaleRoute,
  AuthenticatedCostiStrutturaRoute: AuthenticatedCostiStrutturaRoute,
  AuthenticatedDocumentiRoute: AuthenticatedDocumentiRouteWithChildren,
  AuthenticatedFornitoriRoute: AuthenticatedFornitoriRoute,
  AuthenticatedMaterialiRoute: AuthenticatedMaterialiRoute,
  AuthenticatedNotificheRoute: AuthenticatedNotificheRoute,
  AuthenticatedOrganizzazioneRoute: AuthenticatedOrganizzazioneRoute,
  AuthenticatedProfiloRoute: AuthenticatedProfiloRoute,
  AuthenticatedRapportiniRoute: AuthenticatedRapportiniRouteWithChildren,
  AuthenticatedScadenziarioRoute: AuthenticatedScadenziarioRoute,
  AuthenticatedSubappaltatoriRoute: AuthenticatedSubappaltatoriRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientiClienteIdRoute: AuthenticatedClientiClienteIdRoute,
  AuthenticatedCommesseCommessaIdRoute: AuthenticatedCommesseCommessaIdRoute,
  AuthenticatedPreventiviIdRoute: AuthenticatedPreventiviIdRoute,
  AuthenticatedClientiIndexRoute: AuthenticatedClientiIndexRoute,
  AuthenticatedCommesseIndexRoute: AuthenticatedCommesseIndexRoute,
  AuthenticatedPreventiviIndexRoute: AuthenticatedPreventiviIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccettaInvitoRoute: AccettaInvitoRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
