/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedScadenziarioRouteImport } from './routes/_authenticated/scadenziario'
import { Route as AuthenticatedRapportiniRouteImport } from './routes/_authenticated/rapportini'
import { Route as AuthenticatedPreventiviRouteImport } from './routes/_authenticated/preventivi'
import { Route as AuthenticatedFornitoriRouteImport } from './routes/_authenticated/fornitori'
import { Route as AuthenticatedDocumentiRouteImport } from './routes/_authenticated/documenti'
import { Route as AuthenticatedCommesseRouteImport } from './routes/_authenticated/commesse'
import { Route as AuthenticatedClientiRouteImport } from './routes/_authenticated/clienti'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScadenziarioRoute =
  AuthenticatedScadenziarioRouteImport.update({
    id: '/scadenziario',
    path: '/scadenziario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRapportiniRoute = AuthenticatedRapportiniRouteImport.update({
  id: '/rapportini',
  path: '/rapportini',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreventiviRoute = AuthenticatedPreventiviRouteImport.update({
  id: '/preventivi',
  path: '/preventivi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornitoriRoute = AuthenticatedFornitoriRouteImport.update({
  id: '/fornitori',
  path: '/fornitori',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentiRoute = AuthenticatedDocumentiRouteImport.update({
  id: '/documenti',
  path: '/documenti',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommesseRoute = AuthenticatedCommesseRouteImport.update({
  id: '/commesse',
  path: '/commesse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientiRoute = AuthenticatedClientiRouteImport.update({
  id: '/clienti',
  path: '/clienti',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/clienti': typeof AuthenticatedClientiRoute
  '/commesse': typeof AuthenticatedCommesseRoute
  '/documenti': typeof AuthenticatedDocumentiRoute
  '/fornitori': typeof AuthenticatedFornitoriRoute
  '/preventivi': typeof AuthenticatedPreventiviRoute
  '/rapportini': typeof AuthenticatedRapportiniRoute
  '/scadenziario': typeof AuthenticatedScadenziarioRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/clienti': typeof AuthenticatedClientiRoute
  '/commesse': typeof AuthenticatedCommesseRoute
  '/documenti': typeof AuthenticatedDocumentiRoute
  '/fornitori': typeof AuthenticatedFornitoriRoute
  '/preventivi': typeof AuthenticatedPreventiviRoute
  '/rapportini': typeof AuthenticatedRapportiniRoute
  '/scadenziario': typeof AuthenticatedScadenziarioRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/clienti': typeof AuthenticatedClientiRoute
  '/_authenticated/commesse': typeof AuthenticatedCommesseRoute
  '/_authenticated/documenti': typeof AuthenticatedDocumentiRoute
  '/_authenticated/fornitori': typeof AuthenticatedFornitoriRoute
  '/_authenticated/preventivi': typeof AuthenticatedPreventiviRoute
  '/_authenticated/rapportini': typeof AuthenticatedRapportiniRoute
  '/_authenticated/scadenziario': typeof AuthenticatedScadenziarioRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audit'
    | '/clienti'
    | '/commesse'
    | '/documenti'
    | '/fornitori'
    | '/preventivi'
    | '/rapportini'
    | '/scadenziario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/audit'
    | '/clienti'
    | '/commesse'
    | '/documenti'
    | '/fornitori'
    | '/preventivi'
    | '/rapportini'
    | '/scadenziario'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audit'
    | '/_authenticated/clienti'
    | '/_authenticated/commesse'
    | '/_authenticated/documenti'
    | '/_authenticated/fornitori'
    | '/_authenticated/preventivi'
    | '/_authenticated/rapportini'
    | '/_authenticated/scadenziario'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scadenziario': {
      id: '/_authenticated/scadenziario'
      path: '/scadenziario'
      fullPath: '/scadenziario'
      preLoaderRoute: typeof AuthenticatedScadenziarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapportini': {
      id: '/_authenticated/rapportini'
      path: '/rapportini'
      fullPath: '/rapportini'
      preLoaderRoute: typeof AuthenticatedRapportiniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preventivi': {
      id: '/_authenticated/preventivi'
      path: '/preventivi'
      fullPath: '/preventivi'
      preLoaderRoute: typeof AuthenticatedPreventiviRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornitori': {
      id: '/_authenticated/fornitori'
      path: '/fornitori'
      fullPath: '/fornitori'
      preLoaderRoute: typeof AuthenticatedFornitoriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documenti': {
      id: '/_authenticated/documenti'
      path: '/documenti'
      fullPath: '/documenti'
      preLoaderRoute: typeof AuthenticatedDocumentiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commesse': {
      id: '/_authenticated/commesse'
      path: '/commesse'
      fullPath: '/commesse'
      preLoaderRoute: typeof AuthenticatedCommesseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clienti': {
      id: '/_authenticated/clienti'
      path: '/clienti'
      fullPath: '/clienti'
      preLoaderRoute: typeof AuthenticatedClientiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedClientiRoute: typeof AuthenticatedClientiRoute
  AuthenticatedCommesseRoute: typeof AuthenticatedCommesseRoute
  AuthenticatedDocumentiRoute: typeof AuthenticatedDocumentiRoute
  AuthenticatedFornitoriRoute: typeof AuthenticatedFornitoriRoute
  AuthenticatedPreventiviRoute: typeof AuthenticatedPreventiviRoute
  AuthenticatedRapportiniRoute: typeof AuthenticatedRapportiniRoute
  AuthenticatedScadenziarioRoute: typeof AuthenticatedScadenziarioRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedClientiRoute: AuthenticatedClientiRoute,
  AuthenticatedCommesseRoute: AuthenticatedCommesseRoute,
  AuthenticatedDocumentiRoute: AuthenticatedDocumentiRoute,
  AuthenticatedFornitoriRoute: AuthenticatedFornitoriRoute,
  AuthenticatedPreventiviRoute: AuthenticatedPreventiviRoute,
  AuthenticatedRapportiniRoute: AuthenticatedRapportiniRoute,
  AuthenticatedScadenziarioRoute: AuthenticatedScadenziarioRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
